import type { Product, Category } from "@/types/database";

export const MOCK_CATEGORIES: Category[] = [
  { id: "1", name: "Web Applications", name_fa: "وب اپلیکیشن", slug: "web-applications", description: "پروژه‌های فول‌استک و وب", icon: "Code2", created_at: "", updated_at: "" },
  { id: "2", name: "Mobile Apps", name_fa: "موبایل", slug: "mobile-apps", description: "اپلیکیشن‌های React Native و Flutter", icon: "Zap", created_at: "", updated_at: "" },
  { id: "3", name: "WordPress & CMS", name_fa: "وردپرس", slug: "wordpress", description: "قالب و پلاگین‌های اختصاصی", icon: "Award", created_at: "", updated_at: "" },
  { id: "4", name: "E-Commerce", name_fa: "فروشگاهی", slug: "ecommerce", description: "فروشگاه‌های آنلاین آماده", icon: "TrendingUp", created_at: "", updated_at: "" },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "E-commerce Dashboard",
    title_fa: "داشبورد فروشگاه آنلاین",
    slug: "ecommerce-dashboard",
    category: { id: "4", name: "E-Commerce", name_fa: "فروشگاهی", slug: "ecommerce", description: "فروشگاه‌های آنلاین آماده", created_at: "", updated_at: "" },
    description_fa: "داشبورد کامل مدیریت فروشگاه با قابلیت‌های پیشرفته مدیریت محصولات، سفارشات و گزارشات مالی.",
    short_description_fa: "داشبورد مدیریت فروشگاه با React و Next.js",
    price: 2500000,
    discount_price: 1750000,
    difficulty_level: "intermediate",
    thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    demo_url: "https://demo.example.com",
    rating_average: 4.9,
    rating_count: 128,
    sales_count: 450,
    is_featured: true,
    is_active: true,
    version: "2.0.0",
    view_count: 1250,
    support_duration_months: 6,
    includes_source_code: true,
    includes_documentation: true,
    includes_database: true,
    includes_video_tutorial: true,
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
    technologies: [
      { id: "1", name: "React", slug: "react", created_at: "" },
      { id: "2", name: "Next.js", slug: "nextjs", created_at: "" },
      { id: "3", name: "Tailwind", slug: "tailwind", created_at: "" },
    ],
  },
  {
    id: "2",
    title: "Blog Platform Pro",
    title_fa: "پلتفرم بلاگ حرفه‌ای",
    slug: "blog-platform",
    category: { id: "3", name: "WordPress and CMS", name_fa: "وردپرس", slug: "wordpress", description: "قالب و پلاگین", created_at: "", updated_at: "" },
    description_fa: "سیستم مدیریت محتوای مدرن با پنل ادمین قدرتمند، ادیتور پیشرفته و سئو خودکار.",
    short_description_fa: "سیستم مدیریت محتوا با Laravel و Vue.js",
    price: 1800000,
    difficulty_level: "beginner",
    thumbnail_url: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80",
    rating_average: 4.7,
    rating_count: 89,
    sales_count: 320,
    is_featured: true,
    is_active: true,
    version: "1.5.0",
    view_count: 980,
    support_duration_months: 6,
    includes_source_code: true,
    includes_documentation: true,
    includes_database: true,
    includes_video_tutorial: false,
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
    technologies: [
      { id: "4", name: "Laravel", slug: "laravel", created_at: "" },
      { id: "5", name: "Vue.js", slug: "vuejs", created_at: "" },
    ],
  },
  {
    id: "3",
    title: "Mobile App Template",
    title_fa: "قالب اپلیکیشن موبایل",
    slug: "mobile-app-template",
    category: { id: "2", name: "Mobile Apps", name_fa: "موبایل", slug: "mobile-apps", description: "اپ موبایل", created_at: "", updated_at: "" },
    description_fa: "کیت کامل رابط کاربری موبایل با بیش از ۵۰ صفحه آماده، ناوبری روان و استیت منیجمنت.",
    short_description_fa: "اپلیکیشن موبایل با React Native و Expo",
    price: 3200000,
    discount_price: 2400000,
    difficulty_level: "advanced",
    thumbnail_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    rating_average: 4.8,
    rating_count: 156,
    sales_count: 280,
    is_featured: true,
    is_active: true,
    version: "3.0.0",
    view_count: 1400,
    support_duration_months: 6,
    includes_source_code: true,
    includes_documentation: true,
    includes_database: false,
    includes_video_tutorial: true,
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
    technologies: [
      { id: "6", name: "React Native", slug: "react-native", created_at: "" },
      { id: "7", name: "TypeScript", slug: "typescript", created_at: "" },
    ],
  },
  {
    id: "4",
    title: "Enterprise Admin Panel",
    title_fa: "پنل مدیریت سازمانی",
    slug: "admin-panel",
    category: { id: "1", name: "Web Applications", name_fa: "وب اپلیکیشن", slug: "web-applications", description: "پروژه وب", created_at: "", updated_at: "" },
    description_fa: "داشبورد مدیریتی با احراز هویت دوعاملی، نقش‌های دسترسی چندگانه و نمودارهای تحلیلی زنده.",
    short_description_fa: "پنل ادمین سازمانی با Node.js و React",
    price: 2100000,
    difficulty_level: "intermediate",
    thumbnail_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    rating_average: 4.6,
    rating_count: 72,
    sales_count: 195,
    is_featured: false,
    is_active: true,
    version: "1.8.0",
    view_count: 750,
    support_duration_months: 6,
    includes_source_code: true,
    includes_documentation: true,
    includes_database: true,
    includes_video_tutorial: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-25T00:00:00Z",
    technologies: [
      { id: "1", name: "React", slug: "react", created_at: "" },
      { id: "8", name: "Node.js", slug: "nodejs", created_at: "" },
    ],
  },
];
